### PR TITLE
Fix apollo-client typos.

### PR DESCRIPTION
**Pull request by unamaria**

### CODE REVIEW

**Comment by unamaria** [comment]
Some more feedback in case it's useful :)

- [This sentence](https://github.com/the-road-to-graphql/the-road-to-graphql/blame/master/manuscript/06-apollo-client/index.md#L268) sounds a bit confusing to me:
> Solving the exercises will fortify your GraphQL skills you can focus on connecting the Apollo Client to your React application.

- One of the answers to this question from the quiz was a bit confusing to me too. From it, I was expecting the `cursor` field to be in `node` instead of in `edges`.
screen shot 2018-11-25 at 2 27 53 pm

- I got this in the terminal:
```
{ data:
   { organization:
      { name: 'The Road to learn React',
        url: 'https://github.com/the-road-to-learn-react',
        description: 'Free ebook to learn the fundamentals of React in a practical way by building an application yourself.',
        repositories: [Object],
        __typename: 'Organization' } },
  loading: false,
  networkStatus: 7,
  stale: false }
```
I used GraphiQL to unpack the contents of repositories, but I wonder why it prints `[Object]` instead of its contents.

Super cool chapter, love the quizzes too!

**Comment by rwieruch** [comment]
Thank you @unamaria I will check your suggestions and improve them! Hope you still have lots of fun :)

**Comment by rwieruch** [comment]
The quiz was a bit misleading. My bad! The state should be "GraphQL edges and nodes is the only way to implement pagination in GraphQL." to be wrong, because there are other ways to implement it.

**Comment by rwieruch** [comment]
Improved the sentence to: "Solving the exercises will fortify your GraphQL skills, so that you can later focus on connecting the Apollo Client to your React application without any obstacles.".

**Comment by unamaria** [comment]
Thank you! I am :)

**Pull request merged**
